services:
  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-document-system
    ports:
      - "8501:8501"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CHUNK_SIZE=${CHUNK_SIZE:-1000}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-200}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-sentence-transformers/all-MiniLM-L6-v2}
      - PERSIST_DIRECTORY=/app/chroma_db
      - LLM_TEMPERATURE=${LLM_TEMPERATURE:-0.3}
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./documents:/app/documents
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3